### ISSUE TITLE
Ebooks not in folders

### ISSUE THREAD

**Issue by pgarberg** [getBoolean/jln2kavita#5]
Was just wondering, as it wasn't clear from the ReadMe, if this is able to take ebooks that are not in their own folders, ie. single ebooks in a main folder, and automatically separate them into their own folders. 

If not, is this something that could be implemented, or do you have any suggested alternatives?

**Comment by getBoolean** [comment]
No it doesn't, this script uses the subfolder name from `/Main Folder/AnySubfolder/**.epub` as the series name. In this case, `AnySubfolder` would be the series name in Kavita. Any ebooks in the root `/Main Folder/` are ignored.

I assume you want to use this for a book usenet/torrents downloads folder? That would require using a book metadata API to get the series name and/or author, which I haven't done and I'm not aware of any reliable/comprehensive options for that api. I dont know of any alternatives right now.

If you use this script, you'll have to manually group your novels into folders first. This script will set metadata on the epubs so that Kavita groups and sorts them correctly

I've been thinking of making something like Readarr but compatible with Kavita but thats a massive project, no guarantees it ever gets done. Itll be a separate project from this script.

**Comment by getBoolean** [comment]
How exactly do you want these books grouped? And are these files similar in name, or follow the same naming format? Maybe I can do something with the filename instead of a metadata api, but I need more info

**Comment by getBoolean** [comment]
I've improved the readme, it should be more clear how it works for series folders now. Thanks for the feedback.

**Comment by pgarberg** [comment]
Hey, thank you so much for the quick response!

Your assumption was correct, I had a single folder on an Unraid server where my files would be located. 

Some of those files I had migrated over from a previous Calibre Library with that structure (Author/Book Title/file) others were just "loose" ebooks without any folders. 

After you messaged back, I sat down to try to come up with my own makeshift solution. 

I wrote a script in Javascript which will scan a given folder and, 

1. Identify any epubs (need to implement it for mobi or other formats), 
2. Pull the ebook metadata
3. Based on the author metadata in the ebook, creates an author folder (if one doesn't already exist from the Calibre Library) and then 
4. Based on the title metadata in the ebook,creates a folder based on the book title in the author folder 
5. Moves the ebook into the newly created folder 

It is pretty rudimentary at the moment, am thinking of trying to add some sort of GUI. Would love for it to be implemented in another program (such as Kavita or Audiobookshelf). But for the time being, it does what I need it to do!
